-- AlterTable
ALTER TABLE "Request" ALTER COLUMN "opmeCost" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "psaCost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "RequestResponse" ALTER COLUMN "opmeCost" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "procedureCost" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ticketCost" SET DATA TYPE DOUBLE PRECISION;
