/*
  Warnings:

  - The values [AGUARDANDO_CHEM_3] on the enum `RequestStatus` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RequestStatus_new" AS ENUM ('AGUARDANDO_CHEFE_FUSEX_1', 'AGUARDANDO_CHEFE_AUDITORIA_1', 'AGUARDANDO_AUDITOR', 'AGUARDANDO_CHEFE_AUDITORIA_2', 'AGUARDANDO_CHEFE_FUSEX_2', 'AGUARDANDO_HOMOLOGADOR_SOLICITANTE_1', 'AGUARDANDO_HOMOLOGADOR_SOLICITADA_1', 'AGUARDANDO_CHEFE_DIV_MEDICINA_1', 'AGUARDANDO_ESPECIALISTA', 'AGUARDANDO_CHEFE_DIV_MEDICINA_2', 'AGUARDANDO_COTACAO', 'AGUARDANDO_CHEFE_DIV_MEDICINA_3', 'AGUARDANDO_HOMOLOGADOR_SOLICITADA_2', 'AGUARDANDO_HOMOLOGADOR_SOLICITANTE_2', 'AGUARDANDO_CHEFE_FUSEX_3', 'AGUARDANDO_PASSAGEM', 'AGUARDANDO_CHEFE_FUSEX_4', 'AGUARDANDO_HOMOLOGADOR_SOLICITANTE_3', 'AGUARDANDO_CHEM_1', 'AGUARDANDO_CHEFE_SECAO_REGIONAL_1', 'AGUARDANDO_OPERADOR_SECAO_REGIONAL', 'AGUARDANDO_CHEFE_SECAO_REGIONAL_2', 'AGUARDANDO_CHEM_2', 'AGUARDANDO_SUBDIRETOR_SAUDE_1', 'AGUARDANDO_DRAS', 'AGUARDANDO_SUBDIRETOR_SAUDE_2', 'AGUARDANDO_CHEFE_DIV_MEDICINA_4', 'AGUARDANDO_CHEFE_SECAO_REGIONAL_3', 'AGUARDANDO_RESPOSTA', 'AGUARDANDO_OPERADOR_FUSEX_CUSTOS', 'REPROVADO', 'NECESSITA_CORRECAO', 'REPROVADO_DSAU', 'CANCELADO', 'APROVADO', 'APROVADO_DSAU');
ALTER TABLE "RequestResponse" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Request" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Request" ALTER COLUMN "status" TYPE "RequestStatus_new" USING ("status"::text::"RequestStatus_new");
ALTER TABLE "RequestResponse" ALTER COLUMN "status" TYPE "RequestStatus_new" USING ("status"::text::"RequestStatus_new");
ALTER TYPE "RequestStatus" RENAME TO "RequestStatus_old";
ALTER TYPE "RequestStatus_new" RENAME TO "RequestStatus";
DROP TYPE "RequestStatus_old";
ALTER TABLE "RequestResponse" ALTER COLUMN "status" SET DEFAULT 'AGUARDANDO_HOMOLOGADOR_SOLICITADA_1';
ALTER TABLE "Request" ALTER COLUMN "status" SET DEFAULT 'AGUARDANDO_CHEFE_FUSEX_1';
COMMIT;
